name: Test and update oc.user images

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [dispatch-from-oc.user]
jobs:
  update_image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BASE_IMAGE_RELEASE: [18.04, 20.04, 21.04]
    steps: 
  
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
      with:
        remote: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build image abcdesktopio/oc.user.tunnel.${{ matrix.BASE_IMAGE_RELEASE }}
      run: |
        docker build . -t abcdesktopio/oc.user.tunnel.${{ matrix.BASE_IMAGE_RELEASE }}:dev --build-arg BASE_IMAGE_RELEASE:${{ matrix.BASE_IMAGE_RELEASE }} --build-arg BASE_IMAGE=abcdesktopio/oc.user.${{ matrix.BASE_IMAGE_RELEASE }} --build-arg TAG:dev
   
    - name: Push image abcdesktopio/ic.user.tunnel.${{ matrix.BASE_IMAGE_RELEASE }}
      run: |
        docker push abcdesktopio/oc.user.tunnel.${{ matrix.BASE_IMAGE_RELEASE }}:dev
